import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID} from 'node:crypto';
import {priceStay,authoritativeQuote,validateOccupancy} from '../lib/direct-pricing.js';
import {createPreparationService,normalizedGuest,preparationConfig} from '../lib/direct-checkout-preparation.js';
import {createDirectCheckoutHandler} from '../api/direct-checkout.js';
const config=JSON.parse(fs.readFileSync(new URL('../config/properties.json',import.meta.url)));const rules=JSON.parse(fs.readFileSync(new URL('../config/checkout-properties.json',import.meta.url)));
const prop=(config.properties||config)[0];const options={checkoutProperties:rules,termsVersion:'fixture-v1',termsUrl:'https://example.invalid/fixture-terms',now:new Date('2026-09-01T10:00:00Z')};
const input={property_slug:prop.property_slug,arrival:'2026-09-10',departure:'2026-09-13',adults:2,children:0};
test('single-season integer cents and fee',()=>{const q=authoritativeQuote(config,input,options);assert.equal(q.accommodation_cents,2100000);assert.equal(q.cleaning_cents,100000);assert.equal(q.total_cents,2200000);assert.equal(q.due_now_cents,1100000);});
test('cross-season nightly dates and minimum',()=>{const q=priceStay(prop,'2026-09-29','2026-10-02');assert.deepEqual(q.breakdown.map(n=>n.rate_cents),[700000,700000,600000]);assert.equal(q.total_cents,2100000);assert.equal(q.min_stay_required,3);});
for(const [arrival,dueAll] of [['2026-09-08',true],['2026-09-07',true],['2026-09-09',false]])test('schedule boundary '+arrival,()=>{const q=authoritativeQuote(config,{...input,arrival,departure:'2026-09-15'},options);assert.equal(q.due_now_cents,dueAll?q.total_cents:Math.ceil(q.total_cents/2));});
test('odd cents remain exact through quote',()=>{const p={...prop,seasons:prop.seasons.map(s=>({...s,nightly_rate_zar:'33.33',cleaning_fee_zar:'0.02'}))};const q=authoritativeQuote({properties:[p]},input,options);assert.equal(q.total_cents,10001);assert.equal(q.due_now_cents,5001);assert.equal(q.balance_cents,5000);});
test('cleaning uses applicable season; mixed conflicting fee fails closed',()=>{const p=structuredClone(prop);p.seasons[2].cleaning_fee_zar=1500;assert.equal(priceStay(p,'2026-09-10','2026-09-13').cleaning_cents,100000);assert.throws(()=>priceStay(p,'2026-11-29','2026-12-08'),/CLEANING_RULE_REQUIRES_REVIEW/);});
test('Easter shoulder rule reused',()=>{assert.equal(priceStay(prop,'2027-03-25','2027-03-29').breakdown[0].rate_cents,700000);});
for(const change of [{property_slug:'unknown'},{arrival:'2026-02-30'},{departure:'2026-09-10'},{departure:'2026-09-09'},{adults:9},{children:-1},{adults:1.5}])test('invalid quote '+JSON.stringify(change),()=>assert.throws(()=>authoritativeQuote(config,{...input,...change},options)));
for(const [slug,a,c,valid] of [['legacy-suiderstrand',8,0,true],['legacy-suiderstrand',8,1,false],['kalay-ridge-villa-struisbaai',6,4,true],['kalay-ridge-villa-struisbaai',7,0,false],['kalay-ridge-villa-struisbaai',5,5,false],['the-pearl-beach-villa-agulhas',8,0,true],['the-pearl-beach-villa-agulhas',10,0,false],['the-pearl-beach-villa-agulhas',6,4,true],['the-pearl-beach-villa-agulhas',7,1,false],['ctonic-ocean-view-villa',10,0,true],['ctonic-ocean-view-villa',6,4,true],['ctonic-ocean-view-villa',7,1,false]])test('occupancy '+slug+' '+a+'/'+c,()=>{if(valid)assert.doesNotThrow(()=>validateOccupancy(rules[slug],a,c));else assert.throws(()=>validateOccupancy(rules[slug],a,c));});
test('Ctonic internal only; no invented external identifiers',()=>{assert.equal(rules['ctonic-ocean-view-villa'].checkout_enabled,false);assert.equal(rules['ctonic-ocean-view-villa'].beds24_room_id,undefined);assert.equal(rules['ctonic-ocean-view-villa'].property_page_url,undefined);assert.throws(()=>authoritativeQuote(config,{...input,property_slug:'ctonic-ocean-view-villa'},options),/PROPERTY_CHECKOUT_DISABLED/);assert.ok(!(config.properties||config).some(p=>p.property_slug==='ctonic-ocean-view-villa'));});
test('missing approved terms fails closed',()=>assert.throws(()=>authoritativeQuote(config,input,{...options,termsVersion:''}),/TERMS_NOT_CONFIGURED/));
function fixture(){let clock=options.now,cfg=structuredClone(config),writes=0;const store=new Map();const settings={...options,key:'synthetic-test-signing-material-only-12345',holdMinutes:30,origin:'https://localhost:3443'};
 const service=createPreparationService({config:()=>cfg,settings:()=>settings,now:()=>clock,request:async(path,{prepared,target,access_hash})=>{
 if(path==='rpc/direct_checkout_status'){const v=[...store.values()].find(v=>v.result.checkout_id===target&&v.prepared.access_hash===access_hash);if(!v)throw Error('not found');return v.result;}
 assert.equal(path,'rpc/direct_prepare_checkout');const key=prepared.idempotency_key,old=store.get(key);if(old){if(JSON.stringify(old.prepared)!==JSON.stringify(prepared))throw Error('CHECKOUT_IDEMPOTENCY_CONFLICT');return old.result;}
 writes++;const result={checkout_id:randomUUID(),state:'preparing',quote:prepared.quote,inventory_protected:false,payment_enabled:false};store.set(key,{prepared,result});return result;
 }});return {service,settings,store,writes:()=>writes,setTime:v=>clock=v,changePrice:()=>{(cfg.properties||cfg)[0].seasons[1].nightly_rate_zar++;}};}
const guest={first_name:'Synthetic',surname:'Guest',email:'test@example.invalid',mobile:'+27000000000'};
async function preparation(f){const quote=await f.service({action:'quote',...input});return {action:'prepare',quote_token:quote.quote_token,idempotency_key:randomUUID(),guest,terms_version:'fixture-v1',terms_accepted:true};}
test('durable prepare contract: same input resolves once; status no PII',async()=>{const f=fixture(),p=await preparation(f);const a=await f.service(p),b=await f.service(p);assert.deepEqual(a,b);assert.equal(f.writes(),1);assert.equal(a.state,'preparing');assert.equal(a.inventory_protected,false);assert.equal(a.payment_enabled,false);const status=await f.service({action:'status',checkout_id:a.checkout_id,quote_token:p.quote_token});assert.deepEqual(status,a);assert.doesNotMatch(JSON.stringify(status),/Synthetic|example.invalid.*email|access_hash/);});
test('same key changed guest rejected',async()=>{const f=fixture(),p=await preparation(f);await f.service(p);await assert.rejects(f.service({...p,guest:{...guest,surname:'Changed'}}),/IDEMPOTENCY/);assert.equal(f.writes(),1);});
test('same key new dates or occupancy quote rejected',async()=>{for(const change of [{arrival:'2026-09-11',departure:'2026-09-14'},{adults:3}]){const f=fixture(),p=await preparation(f);await f.service(p);const q=await f.service({action:'quote',...input,...change});await assert.rejects(f.service({...p,quote_token:q.quote_token}),/IDEMPOTENCY/);assert.equal(f.writes(),1);}});
test('stale version/expiry and modified token rejected without writes',async()=>{for(const mode of ['price','expiry','token']){const f=fixture(),p=await preparation(f);if(mode==='price')f.changePrice();if(mode==='expiry')f.setTime(new Date(+options.now+31*60000));if(mode==='token')p.quote_token+='x';await assert.rejects(f.service(p));assert.equal(f.writes(),0);}});
for(const field of ['total','deposit','balance','cleaning_fee','nightly_rate'])test('browser money rejected: '+field,async()=>{const f=fixture(),p=await preparation(f);await assert.rejects(f.service({...p,[field]:1}),/INVALID_FIELDS/);assert.equal(f.writes(),0);});
test('guest ID/passport and card fields rejected',()=>{for(const field of ['passport','id_number','card_number','cvv'])assert.throws(()=>normalizedGuest({...guest,[field]:'forbidden'}),/INVALID_FIELDS/);});
test('endpoint exact origin/method and generic failure response',async()=>{for(const [method,origin,code] of [['GET','https://localhost:3443',405],['POST','https://evil.invalid',403]]){const h=createDirectCheckoutHandler({settings:()=>({origin:'https://localhost:3443'}),service:()=>assert.fail('no processing')});const r={setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;}};await h({method,headers:{origin,'content-type':'application/json'},body:{}},r);assert.equal(r.code,code);}});
test('new migration only creates sandbox preparation, not provider/ops/money records',()=>{const s=fs.readFileSync(new URL('../supabase/migrations/202609260003_direct_checkout_preparation.sql',import.meta.url),'utf8');assert.match(s,/values\('sandbox'/);assert.match(s,/set state='preparing'/);assert.match(s,/pg_advisory_xact_lock/);assert.match(s,/request_fingerprint=fingerprint/);assert.match(s,/grant execute.*direct_prepare_checkout/s);assert.doesNotMatch(s,/insert into public\.(payment_attempts|payment_events|ops_bookings|ops_stay_opening_positions|ops_payment_records)/);assert.doesNotMatch(s,/alter table public.direct_checkouts/);assert.doesNotMatch(s,/set .*protection_verified/);assert.match(s,/revoke all on public.direct_checkout_preparations from public,anon,authenticated,service_role/);});
