import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {createFinanceHandler} from '../api/staff-finances.js';import {operationsRequest} from '../lib/operations-store.js';
const booking='c1000000-0000-0000-0000-000000000001',rate='c2000000-0000-0000-0000-000000000001',review='c3000000-0000-0000-0000-000000000001';
const nights=Array.from({length:8},(_,i)=>({night:`2026-09-${String(5+i).padStart(2,'0')}`,season:'shoulder',rate_id:rate,default_rate_cents:350000,rate_cents:350000}));
const values=['51480','1175','9385.76','800','Felicia','43269.24','2026-09-11','no','Airbnb payout reference','draft','Initial reconciliation from Airbnb payout statement'];
function setup(mode='fail'){
 const element=tag=>({tag,children:[],handlers:{},value:'',append(...c){this.children.push(...c);},replaceChildren(...c){this.children=c;},insertBefore(n,b){this.children.splice(this.children.indexOf(b),0,n);},addEventListener(k,v){this.handlers[k]=v;},setAttribute(){}});
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,element('div'));return elements.get(id);};const calls=[];
 const d={booking:{id:booking,arrival:'2026-09-05',departure:'2026-09-13',property_slug:'legacy-suiderstrand',source_status:'confirmed'},reviews:[],owner_nights:nights,openings:[],expenses:[],attachments:[],history:[],draft:{}};
 let payload;
 const context=vm.createContext({document:{createElement:element,getElementById:get},Date,Intl,crypto:{randomUUID:()=> 'c4000000-0000-0000-0000-000000000001'},fetch:async(url,o)=>{const body=JSON.parse(o.body);calls.push(body);if(body.action==='review'){payload=body.input;if(mode==='fail')return {ok:false,json:async()=>({error:'Standard rates changed or night invalid; reload before saving'})};if(mode==='network')throw Error('Network unavailable; save outcome unconfirmed');return {ok:true,json:async()=>({saved:true,id:review})};}if(mode==='readfail')throw Error('read failed');return {ok:true,json:async()=>({...d,reviews:mode==='missing'?[]:[{...payload,id:review,rate_nights:nights}]})};}});
 let source=fs.readFileSync(new URL('../public/staff-finances.js',import.meta.url),'utf8');source=source.replace(' globalThis.initStayFinances='," globalThis.testReview=(d)=>{staff={permissions:['finance.read','finance.write']};return reviewForm(d);}; globalThis.initStayFinances=");vm.runInContext(source,context);
 const box=context.testReview(d);const form=box.children.find(x=>x.tag==='form');const inputs=form.children.filter(x=>x.tag==='label').map(x=>x.children[0]);inputs.forEach((x,i)=>x.value=values[i]);return {box,form,inputs,calls,get};
}
const submit=a=>a.form.handlers.submit({preventDefault(){}});
test('exact September amounts and eight shoulder nights reach API as correct cents, without mandatory override reason',async()=>{const a=setup();await submit(a);const p=a.calls[0].input;assert.equal(p.accommodation_cents,5148000);assert.equal(p.cleaning_charge_cents,117500);assert.equal(p.channel_fees_cents,938576);assert.equal(p.cleaner_cost_cents,80000);assert.equal(p.funds_received_cents,4326924);assert.equal(p.funds_as_of,'2026-09-11');assert.equal(p.previous_id,null);assert.equal(p.owner_rate_reason,'');assert.equal(p.owner_nights.length,8);assert.ok(p.owner_nights.every(n=>n.rate_cents===350000&&n.default_rate_cents===350000&&n.rate_id===rate));assert.equal(p.expenses_complete,false);});
test('failure stays beside form, retains values and reports native validation failures',async()=>{const a=setup();await submit(a);const message=a.form.children.find(x=>x.tag==='p');assert.match(message.textContent,/Standard rates changed/);assert.deepEqual(a.inputs.map(x=>x.value),values);a.form.handlers.invalid({target:{validationMessage:'Please fill out this field'}});assert.match(message.textContent,/Please fill/);});
test('saving state blocks double click and identical retry keeps request key',async()=>{const a=setup();const first=submit(a);assert.equal(a.form.children.find(x=>x.tag==='button').textContent,'Saving...');await submit(a);await first;assert.equal(a.calls.length,1);await submit(a);assert.equal(a.calls[0].input.request_key,a.calls[1].input.request_key);});
for(const mode of ['missing','readfail','network'])test('no success when outcome '+mode,async()=>{const a=setup(mode);await submit(a);assert.doesNotMatch(a.form.children.find(x=>x.tag==='p').textContent,/Saved successfully/);assert.deepEqual(a.inputs.map(x=>x.value),values);});
test('success requires returned review ID to appear in freshly loaded booking detail',async()=>{const a=setup('success');await submit(a);assert.deepEqual(a.calls.map(c=>c.action),['review','detail']);assert.ok(a.get('finance-detail').children.some(c=>c.textContent==='Saved successfully — financial review verified.'));});
Object.assign(process.env,{BSTE_STAFF_ENV:'staging',BSTE_OPERATIONS_ENABLED:'true',BSTE_OPERATIONS_STAGING_PROJECT_REF:'abcdefghijklmnopqrst',BSTE_STAFF_SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',BSTE_STAFF_SUPABASE_PUBLIC_KEY:'test-public',BSTE_BEDS24_ACCOUNT_KEY:'test-account',BSTE_STAFF_ORIGIN:'https://localhost:3443'});
test('exact UI payload passes unchanged through finance API to review RPC',async()=>{const a=setup();await submit(a);let forwarded;const handler=createFinanceHandler({authorize:async()=>({staff:{},token:'mock-staff'}),request:async(path,token,o)=>{assert.equal(path,'rpc/ops_finance_write');assert.equal(token,'mock-staff');forwarded=o.body;return review;}});const res={setHeader(){},status(c){this.code=c;return this;},json(b){this.body=b;}};await handler({method:'POST',headers:{origin:'https://localhost:3443','content-type':'application/json'},body:a.calls[0]},res);assert.equal(res.code,200);assert.deepEqual(forwarded,{action_name:'review',input:a.calls[0].input});assert.deepEqual(res.body,{saved:true,id:review});});
test('safe storage errors expose only exact allowlisted validation messages',async()=>{for(const message of ['Stale financial revision; reload','private provider SQL with guest details']){await assert.rejects(operationsRequest('rpc/ops_finance_write','mock',{method:'POST',safeErrors:['Stale financial revision; reload'],fetcher:async()=>Response.json({message,details:'secret details'},{status:400})}),e=>{assert.doesNotMatch(e.message,/secret|private provider/);if(message.startsWith('Stale'))assert.equal(e.message,message);return true;});}});
