import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {financeDiagnostic,createLocalFinanceHandler} from '../scripts/local-finance-diagnostics.mjs';
Object.assign(process.env,{BSTE_STAFF_ENV:'staging',BSTE_OPERATIONS_ENABLED:'true',BSTE_OPERATIONS_STAGING_PROJECT_REF:'abcdefghijklmnopqrst',BSTE_STAFF_SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',BSTE_STAFF_SUPABASE_PUBLIC_KEY:'test-public',BSTE_BEDS24_ACCOUNT_KEY:'test-account',BSTE_STAFF_ORIGIN:'https://localhost:3443'});delete process.env.VERCEL;delete process.env.VERCEL_ENV;
const req=()=>({method:'POST',headers:{origin:'https://localhost:3443',host:'localhost:3443','content-type':'application/json'},socket:{encrypted:true,remoteAddress:'127.0.0.1'},body:{action:'review',input:{}}});
const res=()=>({setHeader(){},status(c){this.code=c;return this;},json(b){this.body=b;}});
test('PostgREST 23514 diagnostic reaches browser and terminal identically without generic rejection',async()=>{
 const logs=[];const h=createLocalFinanceHandler({authorize:async()=>({staff:{},token:'never-log-token'}),log:v=>logs.push(v),fetcher:async()=>Response.json({code:'23514',message:'example safe SQL validation failure',details:null,hint:null},{status:400})});const r=res();await h(req(),r);assert.equal(r.code,409);assert.match(r.body.error,/status=400\ncode=23514\nmessage=example safe SQL validation failure/);assert.equal(logs[0],r.body.error);assert.doesNotMatch(r.body.error,/never-log-token|Operations storage rejected/);
});
test('schema constraint retained but row details, hints and arbitrary messages withheld',()=>{
 const secret='Guest Jane guest@example.org Bearer eyJsecret secret-service-key postgres://credentials';
 const out=financeDiagnostic(400,{code:'23514',message:'new row for relation "ops_stay_financial_reviews" violates check constraint "ops_stay_financial_reviews_check"',details:secret,hint:secret});assert.match(out,/ops_stay_financial_reviews_check/);assert.doesNotMatch(out,/Jane|guest@|Bearer|eyJsecret|secret-service|postgres:/);
 const unknown=financeDiagnostic(400,{code:secret,message:secret});assert.doesNotMatch(unknown,/Jane|guest@|Bearer|eyJsecret|postgres:/);assert.match(unknown,/withheld/);
});
test('invalid input reveals type but never submitted value',()=>{const out=financeDiagnostic(400,{code:'22P02',message:'invalid input syntax for type uuid: "private@example.org"'});assert.match(out,/type uuid/);assert.doesNotMatch(out,/private@/);});
for(const mode of ['remote','unencrypted','wrong origin','production'])test('local diagnostic refuses '+mode,async()=>{const q=req();if(mode==='remote')q.socket.remoteAddress='192.0.2.1';if(mode==='unencrypted')q.socket.encrypted=false;if(mode==='wrong origin')q.headers.origin='https://evil.invalid';if(mode==='production')process.env.VERCEL_ENV='production';try{const h=createLocalFinanceHandler({authorize:async()=>assert.fail('must fail before auth'),fetcher:async()=>assert.fail('no network'),log:()=>assert.fail('no diagnostics')});const r=res();await h(q,r);assert.equal(r.code,403);}finally{delete process.env.VERCEL_ENV;}});
test('diagnostics wired only in scripts server, never deployable finance handler',()=>{const server=fs.readFileSync(new URL('../scripts/staff-staging-server.mjs',import.meta.url),'utf8');const api=fs.readFileSync(new URL('../api/staff-finances.js',import.meta.url),'utf8');assert.match(server,/local-finance-diagnostics/);assert.doesNotMatch(api,/local-finance-diagnostics|onRejected|console.error/);});
test('read-only metadata SQL matches current local function hash',async()=>{const {createHash}=await import('node:crypto');const sql=fs.readFileSync(new URL('../supabase/migrations/202609250001_add_owner_shoulder_and_booking_rate_overrides.sql',import.meta.url),'utf8');const body=sql.split('create or replace function public.ops_finance_write')[1].split('as $$')[1].split('$$;')[0];const query=fs.readFileSync(new URL('../docs/finance-save-function-verification.sql',import.meta.url),'utf8');assert.ok(query.includes(createHash('md5').update(body).digest('hex')));assert.doesNotMatch(query,/\b(insert|update|delete|alter|create|call)\s/i);});
